# Generated by Django 3.2.6 on 2022-01-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppList', '0002_auto_20220108_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.CharField(choices=[('p', 'Pendiente'), ('ep', 'En proceso'), ('r', 'Realizada')], max_length=2),
        ),
    ]
