# Generated by Django 3.2.6 on 2022-01-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppList', '0003_alter_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.CharField(choices=[('E1', 'Pendiente'), ('E2', 'En proceso'), ('E3', 'Realizada')], default='E1', max_length=2),
        ),
    ]
